"use client";

/**
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * Command: npx gltfjsx@6.2.16 .\models\die2_optimised_renamed.glb --output .\src\app\_models\die.tsx --types --transform --debug
 */

import * as THREE from "three";
import React, { RefObject } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { applyColor, invertNormalMap } from "./util";

type GLTFResult = GLTF & {
  nodes: {
    edges: THREE.Mesh;
    faces: THREE.Mesh;
    nuts: THREE.Mesh;
  };
  materials: {
    ["edges BFDFED"]: THREE.MeshStandardMaterial;
    ["faces BFDFED"]: THREE.MeshStandardMaterial;
    ["nuts 59615C"]: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export type DieProps = JSX.IntrinsicElements["group"] & {
  groupRef?: RefObject<THREE.Group>;
};

export function Die(props: DieProps) {
  const { nodes, materials } = useGLTF("/models/die.glb") as GLTFResult;

  const startTime = new Date().getTime();

  for (const [name, material] of Object.entries(materials)) {
    if (material.userData.hasColorBeenApplied) {
      continue;
    }

    try {
      const color = new THREE.Color(`#${material.name.split(" ")[1]}`);
      const coloredMaterial = applyColor(material, color);
      try {
        if (material.normalMap) {
          coloredMaterial.normalMap = invertNormalMap(coloredMaterial);
        }
      } catch (error) {
        console.error(error);
      }

      materials[name as keyof typeof materials] = coloredMaterial;
    } catch (error) {
      console.error(error);
    }
  }

  console.log(
    "Time to render textures:",
    new Date().getTime() - startTime,
    "ms",
  );

  return (
    <group ref={props.groupRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.edges.geometry}
        material={materials["edges BFDFED"]}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.faces.geometry}
        material={materials["faces BFDFED"]}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.nuts.geometry}
        material={materials["nuts 59615C"]}
        castShadow
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload("/models/die.glb");
